#!/bin/bash
[CONF]
base64_key=shid
[CONF_END]
[all]
#egrep  "\<$(sed -n '/HostList/p' psh-UserGroup |cut -d'=' -f2)\>" hosts-YQ.conf
#------云迁移定版环境---------

#NewCore定版
[ncd]
UserName=
HostList0=NCD[0-9].*
[END]

[ncy]
UserName=
HostList0=NCY[0-9].*
[END]

#云迁移定版
[yqd]
UserName=
HostList0=YQD[0-9].*
[END]

#云迁移预演
[yqy]
UserName=
HostList0=YQY[0-9].*
[END]

#定版环境
[d]
UserName=
HostList0=DB[0-9].*
[END]

#预演环境
[y]
UserName=
HostList0=YY[0-9].*
[END]

#双活定版
[sd]
UserName=
HostList0=SD[0-9].*
[END]

#双活预演
[sy]
UserName=
HostList0=SY[0-9].*
[END]


[app]
UserName=
HostList0=NC[DY][0-9].*
HostList0=S[DY][0-9].*
HostList0=YQ[DY][0-9].*
HostList0=DB[0-9].*
HostList0=YY[0-9].*
[END]
